### ISSUE TITLE
pep8

### ISSUE THREAD

**Issue by virvaldium** [hud0shnik/test_tasks#1]
https://github.com/hud0shnik/test_task_mts/blob/dc8e76a1de848f4cd0926166647f33e9bddcd9de/films.py#L1

модуль requests является не стандартным модулем. Он должен находиться ниже импорта стандартных модулей и через пустую строку. Рекомендую почитать PEP8

**Comment by hud0shnik** [comment]
Оформил по стандартам 5aeae88ef5cdb36e2ef86eb5945087fd057e15cf
