### ISSUE TITLE
PEP8

### ISSUE THREAD

**Issue by virvaldium** [hud0shnik/test_tasks#2]
https://github.com/hud0shnik/test_task_mts/blob/dc8e76a1de848f4cd0926166647f33e9bddcd9de/films.py#L5

рекомендую прочитать как необходимо оформлять функции, а как классы в python. Это все регулируется стандартом PEP8. В python разработке этот стандарт важен

**Comment by hud0shnik** [comment]
Оформил по стандартам 5aeae88ef5cdb36e2ef86eb5945087fd057e15cf
