### ISSUE TITLE
Это просто фееричный метод подсчета позиции фильма

### ISSUE THREAD

**Issue by virvaldium** [hud0shnik/test_tasks#3]
https://github.com/hud0shnik/test_task_mts/blob/dc8e76a1de848f4cd0926166647f33e9bddcd9de/films.py#L36

Во первых, правильным вариантом является вытащить номер фильма из div блока с фильмом
Во вторых, чем не угодил обычный счетчик? Условно говоря такого вида i += 1

**Comment by hud0shnik** [comment]
Добавил счётчик (в респонсе Кинопоиска нет блока с местов в рейтинге, на вход приходит уже отсортированный список фильмов) 020708bf6ac38210b7f362fa8d58c3f28861f0de
