### ISSUE TITLE
Это точно правильно отрабатывает? 

### ISSUE THREAD

**Issue by virvaldium** [hud0shnik/test_tasks#4]
https://github.com/hud0shnik/test_task_mts/blob/dc8e76a1de848f4cd0926166647f33e9bddcd9de/films.py#L28

просто эта строчка кода всегда возвращает целочисленный ноль. 
Хотя, возможно это Яндекс меня блокирует...

**Comment by hud0shnik** [comment]
При блокировке Яндексом, на вход поступает страница с капчей, по этому все find возвращают -1, для тестирования без запросов к Яндексу я добавил первую страницу списка ([response_sample.html](https://github.com/hud0shnik/test_task_mts/blob/main/response_sample.html))
