### ISSUE TITLE
Это точно правильно?

### ISSUE THREAD

**Issue by virvaldium** [hud0shnik/test_tasks#5]
https://github.com/hud0shnik/test_task_mts/blob/dc8e76a1de848f4cd0926166647f33e9bddcd9de/films.py#L32

здесь также возвращается ноль. Но, возможно, меня заблокировал Яндекс.
Плюс ко всему не понятно для чего потребовалось перезаписывать в рамках одного цикла переменную left?

**Comment by hud0shnik** [comment]
https://github.com/hud0shnik/test_task_mts/blob/dc8e76a1de848f4cd0926166647f33e9bddcd9de/films.py#L33

Left перезаписывается потому что нужен для обозначения начала искомого значения (индекс крайнего левого символа). После перезаписи вызывается find для поиска индекса конца.
