### ISSUE TITLE
На этом месте произойдет ошибка импорта

### ISSUE THREAD

**Issue by virvaldium** [hud0shnik/test_tasks#6]
https://github.com/hud0shnik/test_task_mts/blob/dc8e76a1de848f4cd0926166647f33e9bddcd9de/films.py#L46

Отсутсвует импорт модуля json. Код не рабочий, так как дойдя до этого места упадет с ImportError. 
Мало того, так как из-за ошибки не выполнится следующая строка, то это означает, что файл открытый на запись не будет корректно закрыт

**Comment by hud0shnik** [comment]
Добавил импорт в 5aeae88ef5cdb36e2ef86eb5945087fd057e15cf
